#!/bin/bash

git clone https://github.com/ColdGrub1384/fastSwift-Server-Installer.git

if [ "$USER" != "root" ]; then echo "Run this as root to create /home/fastswift"; exit; fi
echo "Creating /home/fastswift..."
mkdir /home/fastswift
echo "Copying FFKit.swift to /home/fastswift..."
mv fastSwift-Server-Installer/FFKit.swift /home/fastswift/FFKit.swift
echo "Creating $1 user..."
adduser --disabled-password --gecos "" $1 
echo -e "$2\n$2" | passwd $1
touch /home/fastswift/latest.html
echo "Creating database..."
mkdir /home/$1/.db
check_stat=`ps -ef | grep sshd | grep -v grep | awk '{print $2}'`
if [ "${check_stat}X" != "X" ]
then
echo ""
else
echo "Enable SSH for $SUDO_USER"
fi
echo "Server: $1@$(/sbin/ifconfig | grep -e "inet:" -e "addr:" | grep -v "inet6" | grep -v "127.0.0.1" | head -n 1 | awk '{print $2}' | cut -c6-)"
